# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Wii U File System.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 240)
        Form.setMinimumSize(QtCore.QSize(400, 240))
        Form.setMaximumSize(QtCore.QSize(400, 240))
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Form.setWindowOpacity(1.0)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 100, 402, 141))
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 140))
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Inject = QtWidgets.QWidget()
        self.Inject.setObjectName("Inject")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.Inject)
        self.lineEdit_4.setGeometry(QtCore.QRect(80, 10, 111, 26))
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_4 = QtWidgets.QLabel(self.Inject)
        self.label_4.setGeometry(QtCore.QRect(2, 15, 81, 16))
        self.label_4.setObjectName("label_4")
        self.toolButton_3 = QtWidgets.QToolButton(self.Inject)
        self.toolButton_3.setGeometry(QtCore.QRect(190, 10, 81, 26))
        self.toolButton_3.setObjectName("toolButton_3")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.Inject)
        self.lineEdit_5.setGeometry(QtCore.QRect(80, 40, 111, 26))
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_5 = QtWidgets.QLabel(self.Inject)
        self.label_5.setGeometry(QtCore.QRect(2, 45, 58, 16))
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.Inject)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 70, 90, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_6 = QtWidgets.QLabel(self.Inject)
        self.label_6.setGeometry(QtCore.QRect(200, 45, 81, 16))
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.Inject, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(290, 70, 90, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(2, 15, 81, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(90, 10, 111, 26))
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(210, 15, 101, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_9.setGeometry(QtCore.QRect(90, 40, 111, 26))
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(2, 45, 81, 16))
        self.label_16.setObjectName("label_16")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(310, 20, 81, 31))
        self.pushButton.setObjectName("pushButton")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(2, 25, 91, 16))
        self.label_9.setObjectName("label_9")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_7.setGeometry(QtCore.QRect(100, 20, 113, 26))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.toolButton_5 = QtWidgets.QToolButton(self.tab)
        self.toolButton_5.setGeometry(QtCore.QRect(210, 20, 91, 26))
        self.toolButton_5.setObjectName("toolButton_5")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(2, 0, 321, 16))
        self.label_14.setObjectName("label_14")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_8.setGeometry(QtCore.QRect(100, 50, 113, 26))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(2, 55, 71, 16))
        self.label_10.setObjectName("label_10")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(220, 50, 131, 16))
        self.label_15.setObjectName("label_15")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(2, 50, 221, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(100, 2, 271, 16))
        self.label_12.setObjectName("label_12")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 70, 131, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_5.setGeometry(QtCore.QRect(130, 70, 141, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(2, 0, 41, 16))
        self.label_13.setObjectName("label_13")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_6.setGeometry(QtCore.QRect(270, 70, 126, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.tabWidget.addTab(self.tab_3, "")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(2, 15, 58, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(70, 10, 113, 26))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(5, 45, 58, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 40, 113, 26))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(5, 75, 59, 13))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setGeometry(QtCore.QRect(70, 70, 113, 26))
        self.lineEdit.setObjectName("lineEdit")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(290, 72, 101, 21))
        self.checkBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox.setMouseTracking(False)
        self.checkBox.setObjectName("checkBox")
        self.toolButton = QtWidgets.QToolButton(Form)
        self.toolButton.setEnabled(True)
        self.toolButton.setGeometry(QtCore.QRect(180, 70, 91, 26))
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(Form)
        self.toolButton_2.setGeometry(QtCore.QRect(180, 40, 91, 26))
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_4 = QtWidgets.QToolButton(Form)
        self.toolButton_4.setGeometry(QtCore.QRect(180, 10, 91, 26))
        self.toolButton_4.setObjectName("toolButton_4")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(267, 0, 16, 129))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.checkBox_2 = QtWidgets.QCheckBox(Form)
        self.checkBox_2.setGeometry(QtCore.QRect(290, 12, 87, 21))
        self.checkBox_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_2.setObjectName("checkBox_2")
        self.tabWidget.raise_()
        self.label_3.raise_()
        self.lineEdit_3.raise_()
        self.label_2.raise_()
        self.lineEdit_2.raise_()
        self.label.raise_()
        self.lineEdit.raise_()
        self.checkBox.raise_()
        self.toolButton.raise_()
        self.toolButton_2.raise_()
        self.line.raise_()
        self.checkBox_2.raise_()
        self.toolButton_4.raise_()
        self.label_4.setBuddy(self.lineEdit_4)
        self.label_5.setBuddy(self.lineEdit_4)
        self.label_7.setBuddy(self.lineEdit_4)
        self.label_16.setBuddy(self.lineEdit_4)
        self.label_3.setBuddy(self.lineEdit_3)
        self.label_2.setBuddy(self.lineEdit_2)
        self.label.setBuddy(self.lineEdit)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "File to inject"))
        self.toolButton_3.setText(_translate("Form", "Choose"))
        self.label_5.setText(_translate("Form", "Path"))
        self.pushButton_2.setText(_translate("Form", "Start"))
        self.label_6.setText(_translate("Form", "Ex:/usr/title/"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Inject), _translate("Form", "Inject"))
        self.pushButton_3.setText(_translate("Form", "Start"))
        self.label_7.setText(_translate("Form", "Path to dump"))
        self.label_8.setText(_translate("Form", "Ex:/usr/title/"))
        self.label_16.setText(_translate("Form", "Output dir"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Extract"))
        self.pushButton.setText(_translate("Form", "Mount"))
        self.label_9.setText(_translate("Form", "Mount where ?"))
        self.toolButton_5.setText(_translate("Form", "Choose"))
        self.label_14.setText(_translate("Form", "If Device is checked you don\'t need to create an image"))
        self.label_10.setText(_translate("Form", "Password : "))
        self.label_15.setText(_translate("Form", "root user  are needed"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Mount"))
        self.label_11.setText(_translate("Form", "I begin in QT and it\'s my first program"))
        self.label_12.setText(_translate("Form", "Wii U Fille System QT by TriRetr0"))
        self.pushButton_4.setText(_translate("Form", "Join my Discord"))
        self.pushButton_5.setText(_translate("Form", "Fork my github repo"))
        self.label_13.setText(_translate("Form", "V0.0.1"))
        self.pushButton_6.setText(_translate("Form", "wfs github"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Creator"))
        self.label_3.setText(_translate("Form", "Image"))
        self.label_2.setText(_translate("Form", "OTP"))
        self.label.setText(_translate("Form", "SEEPROM"))
        self.checkBox.setText(_translate("Form", "MLC (NAND)"))
        self.toolButton.setText(_translate("Form", "Choose"))
        self.toolButton_2.setText(_translate("Form", "Choose"))
        self.toolButton_4.setText(_translate("Form", "Choose"))
        self.checkBox_2.setText(_translate("Form", "Device"))

