# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Wii U File System.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(401, 240)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 100, 401, 140))
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Inject = QtWidgets.QWidget()
        self.Inject.setObjectName("Inject")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.Inject)
        self.lineEdit_4.setGeometry(QtCore.QRect(72, 10, 111, 26))
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_4 = QtWidgets.QLabel(self.Inject)
        self.label_4.setGeometry(QtCore.QRect(2, 15, 58, 16))
        self.label_4.setObjectName("label_4")
        self.toolButton_3 = QtWidgets.QToolButton(self.Inject)
        self.toolButton_3.setGeometry(QtCore.QRect(180, 10, 81, 26))
        self.toolButton_3.setObjectName("toolButton_3")
        self.tabWidget.addTab(self.Inject, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(2, 15, 58, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(70, 10, 113, 26))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(5, 45, 58, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 40, 113, 26))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(5, 75, 59, 13))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(70, 70, 113, 26))
        self.lineEdit.setObjectName("lineEdit")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(290, 70, 87, 21))
        self.checkBox.setObjectName("checkBox")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(280, 10, 121, 28))
        self.pushButton.setObjectName("pushButton")
        self.toolButton = QtWidgets.QToolButton(Form)
        self.toolButton.setGeometry(QtCore.QRect(180, 70, 91, 26))
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(Form)
        self.toolButton_2.setGeometry(QtCore.QRect(180, 40, 91, 26))
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_4 = QtWidgets.QToolButton(Form)
        self.toolButton_4.setGeometry(QtCore.QRect(180, 10, 91, 26))
        self.toolButton_4.setObjectName("toolButton_4")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(267, 0, 16, 129))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_4.setBuddy(self.lineEdit_4)
        self.label_3.setBuddy(self.lineEdit_3)
        self.label_2.setBuddy(self.lineEdit_2)
        self.label.setBuddy(self.lineEdit)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.checkBox.clicked.connect(self.lineEdit.hide)
        self.checkBox.clicked.connect(self.label.hide)
        self.checkBox.clicked['bool'].connect(self.label.show)
        self.checkBox.clicked['bool'].connect(self.lineEdit.show)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "File"))
        self.toolButton_3.setText(_translate("Form", "Choose"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Inject), _translate("Form", "Inject"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Extract"))
        self.label_3.setText(_translate("Form", "Image"))
        self.label_2.setText(_translate("Form", "OTP"))
        self.label.setText(_translate("Form", "SEEPROM"))
        self.checkBox.setText(_translate("Form", "MLC"))
        self.pushButton.setText(_translate("Form", "Mount with fuse"))
        self.toolButton.setText(_translate("Form", "Choose"))
        self.toolButton_2.setText(_translate("Form", "Choose"))
        self.toolButton_4.setText(_translate("Form", "Choose"))

